### PR TITLE
Updated gem to support token

### PR DESCRIPTION
**Pull request by cammellos**
Hi,
I have updated the gem as now Faroo requires the use of an api key, I have also removed threads as they hit the api limit. I wrote the specs with rspec and vcr, feel free to merge the changes, but I had to change the public api.
Thanks

### CODE REVIEW

**Comment by pld** [comment]
@cammellos this is some great work, thanks for the PR and sorry about the delay

**Comment by pld** [comment]
When running `rspec` I get a bunch of failures, do you see these too?

```
.FFFFFF.FFFFFF

Failures:

  1) Faroo Faroo::news returns some results
     Failure/Error: expect(api.send(method,"test").empty?).to eq(false)
     URI::InvalidURIError:
       bad URI(is not URI?): http://www.faroo.com/api?key=<TOKEN>&l=en&length=10&q=test&src=news&start=1
     # ./lib/faroo.rb:55:in `search'
     # ./lib/faroo.rb:39:in `news'
     # ./spec/cases/api_spec.rb:17:in `block (5 levels) in <top (required)>'
     # ./spec/cases/api_spec.rb:15:in `block (4 levels) in <top (required)>'

  2) Faroo Faroo::news returns the correct number of results
     Failure/Error: expect(api.send(method,"test").length).to eq(8)
     URI::InvalidURIError:
       bad URI(is not URI?): http://www.faroo.com/api?key=<TOKEN>&l=en&length=8&q=test&src=news&start=1
     # ./lib/faroo.rb:55:in `search'
     # ./lib/faroo.rb:39:in `news'
     # ./spec/cases/api_spec.rb:23:in `block (5 levels) in <top (required)>'
     # ./spec/cases/api_spec.rb:21:in `block (4 levels) in <top (required)>'

  3) Faroo Faroo::news return the same result using the same cassette
     Failure/Error: result1 = api.send(method,"test")
     URI::InvalidURIError:
       bad URI(is not URI?): http://www.faroo.com/api?key=<TOKEN>&l=en&length=10&q=test&src=news&start=1
     # ./lib/faroo.rb:55:in `search'
     # ./lib/faroo.rb:39:in `news'
     # ./spec/cases/api_spec.rb:29:in `block (5 levels) in <top (required)>'
     # ./spec/cases/api_spec.rb:27:in `block (4 levels) in <top (required)>'

  4) Faroo Faroo::news return different results using the start parameters
     Failure/Error: result1 = api.send(method,"test")
     URI::InvalidURIError:
       bad URI(is not URI?): http://www.faroo.com/api?key=<TOKEN>&l=en&length=10&q=test&src=news&start=1
     # ./lib/faroo.rb:55:in `search'
     # ./lib/faroo.rb:39:in `news'
     # ./spec/cases/api_spec.rb:39:in `block (5 levels) in <top (required)>'
     # ./spec/cases/api_spec.rb:37:in `block (4 levels) in <top (required)>'

  5) Faroo Faroo::news return different results using the language parameters
     Failure/Error: result1 = api.send(method,"test")
     URI::InvalidURIError:
       bad URI(is not URI?): http://www.faroo.com/api?key=<TOKEN>&l=en&length=10&q=test&src=news&start=1
     # ./lib/faroo.rb:55:in `search'
     # ./lib/faroo.rb:39:in `news'
     # ./spec/cases/api_spec.rb:49:in `block (5 levels) in <top (required)>'
     # ./spec/cases/api_spec.rb:47:in `block (4 levels) in <top (required)>'

  6) Faroo Faroo::news return empty if no results
     Failure/Error: expect(api.send(method,"ahtneanhean").empty?).to eq(true)
     URI::InvalidURIError:
       bad URI(is not URI?): http://www.faroo.com/api?key=<TOKEN>&l=en&length=10&q=ahtneanhean&src=news&start=1
     # ./lib/faroo.rb:55:in `search'
     # ./lib/faroo.rb:39:in `news'
     # ./spec/cases/api_spec.rb:59:in `block (5 levels) in <top (required)>'
     # ./spec/cases/api_spec.rb:57:in `block (4 levels) in <top (required)>'

  7) Faroo Faroo::web returns some results
     Failure/Error: expect(api.send(method,"test").empty?).to eq(false)
     URI::InvalidURIError:
       bad URI(is not URI?): http://www.faroo.com/api?key=<TOKEN>&l=en&length=10&q=test&src=web&start=1
     # ./lib/faroo.rb:55:in `search'
     # ./lib/faroo.rb:35:in `web'
     # ./spec/cases/api_spec.rb:17:in `block (5 levels) in <top (required)>'
     # ./spec/cases/api_spec.rb:15:in `block (4 levels) in <top (required)>'

  8) Faroo Faroo::web returns the correct number of results
     Failure/Error: expect(api.send(method,"test").length).to eq(8)
     URI::InvalidURIError:
       bad URI(is not URI?): http://www.faroo.com/api?key=<TOKEN>&l=en&length=8&q=test&src=web&start=1
     # ./lib/faroo.rb:55:in `search'
     # ./lib/faroo.rb:35:in `web'
     # ./spec/cases/api_spec.rb:23:in `block (5 levels) in <top (required)>'
     # ./spec/cases/api_spec.rb:21:in `block (4 levels) in <top (required)>'

  9) Faroo Faroo::web return the same result using the same cassette
     Failure/Error: result1 = api.send(method,"test")
     URI::InvalidURIError:
       bad URI(is not URI?): http://www.faroo.com/api?key=<TOKEN>&l=en&length=10&q=test&src=web&start=1
     # ./lib/faroo.rb:55:in `search'
     # ./lib/faroo.rb:35:in `web'
     # ./spec/cases/api_spec.rb:29:in `block (5 levels) in <top (required)>'
     # ./spec/cases/api_spec.rb:27:in `block (4 levels) in <top (required)>'

  10) Faroo Faroo::web return different results using the start parameters
     Failure/Error: result1 = api.send(method,"test")
     URI::InvalidURIError:
       bad URI(is not URI?): http://www.faroo.com/api?key=<TOKEN>&l=en&length=10&q=test&src=web&start=1
     # ./lib/faroo.rb:55:in `search'
     # ./lib/faroo.rb:35:in `web'
     # ./spec/cases/api_spec.rb:39:in `block (5 levels) in <top (required)>'
     # ./spec/cases/api_spec.rb:37:in `block (4 levels) in <top (required)>'

  11) Faroo Faroo::web return different results using the language parameters
     Failure/Error: result1 = api.send(method,"test")
     URI::InvalidURIError:
       bad URI(is not URI?): http://www.faroo.com/api?key=<TOKEN>&l=en&length=10&q=test&src=web&start=1
     # ./lib/faroo.rb:55:in `search'
     # ./lib/faroo.rb:35:in `web'
     # ./spec/cases/api_spec.rb:49:in `block (5 levels) in <top (required)>'
     # ./spec/cases/api_spec.rb:47:in `block (4 levels) in <top (required)>'

  12) Faroo Faroo::web return empty if no results
     Failure/Error: expect(api.send(method,"ahtneanhean").empty?).to eq(true)
     URI::InvalidURIError:
       bad URI(is not URI?): http://www.faroo.com/api?key=<TOKEN>&l=en&length=10&q=ahtneanhean&src=web&start=1
     # ./lib/faroo.rb:55:in `search'
     # ./lib/faroo.rb:35:in `web'
     # ./spec/cases/api_spec.rb:59:in `block (5 levels) in <top (required)>'
     # ./spec/cases/api_spec.rb:57:in `block (4 levels) in <top (required)>'

Finished in 0.09838 seconds (files took 0.27316 seconds to load)
14 examples, 12 failures

Failed examples:

rspec ./spec/cases/api_spec.rb:14 # Faroo Faroo::news returns some results
rspec ./spec/cases/api_spec.rb:20 # Faroo Faroo::news returns the correct number of results
rspec ./spec/cases/api_spec.rb:26 # Faroo Faroo::news return the same result using the same cassette
rspec ./spec/cases/api_spec.rb:36 # Faroo Faroo::news return different results using the start parameters
rspec ./spec/cases/api_spec.rb:46 # Faroo Faroo::news return different results using the language parameters
rspec ./spec/cases/api_spec.rb:56 # Faroo Faroo::news return empty if no results
rspec ./spec/cases/api_spec.rb:14 # Faroo Faroo::web returns some results
rspec ./spec/cases/api_spec.rb:20 # Faroo Faroo::web returns the correct number of results
rspec ./spec/cases/api_spec.rb:26 # Faroo Faroo::web return the same result using the same cassette
rspec ./spec/cases/api_spec.rb:36 # Faroo Faroo::web return different results using the start parameters
rspec ./spec/cases/api_spec.rb:46 # Faroo Faroo::web return different results using the language parameters
rspec ./spec/cases/api_spec.rb:56 # Faroo Faroo::web return empty if no results
```

**Comment by cammellos** [comment]
Hi Peter,
thanks for the reply, I am using VCR to record the requests, I have used my token to generate the fixtures and used filter_sensitive_data to remove the private token from the YAML files. The tests should be passing by using the command
TOKEN="any-string-should-work" bundle exec rspec 
(I have updated the README as well). TOKEN can be set to anything.
Essentially I was following http://stackoverflow.com/questions/9816152/filtering-sensitive-data-with-vcr 
Let me know if that's ok.

**Comment by pld** [comment]
Great! I've verified that works, merging

**Pull request merged**
